// Fillio UI translations. User-authored content is never passed through t().
const I18N={
 ja:{
  "library.title":"Library","library.newProject":"＋ プロジェクト","library.newFolder":"＋ フォルダ","library.projects":"作品一覧",
  "settings.title":"アプリ設定","settings.language":"言語","settings.defaults":"新規プロジェクトのデフォルト","settings.pages":"制作ページ","settings.stages":"工程","settings.addStage":"＋ 工程を追加","common.cancel":"キャンセル","common.save":"保存","common.close":"閉じる","settings.note":"新しいプロジェクトを作るときの初期値です。プロジェクトごとに変更できます。","notes.title":"メモ一覧",
  "settings.displayMode":"表示モード","settings.displayModeNote":"画面の明るさを選べます。自動は端末の設定に合わせます。","settings.themeColor":"テーマカラー","settings.themeColorNote":"完了セルや選択状態などのアクセントカラーに使われます。","settings.cellShape":"セル形状","settings.cellShapeNote":"タッチ領域はそのまま、セルの見た目だけを変更します。","settings.dataManagement":"データ管理","settings.dataManagementNote":"全作品・フォルダ・進捗・付箋・作業履歴を1つのJSONに保存します。","settings.backup":"💾 バックアップ","settings.restore":"📂 復元","backup.saved":"✅ 全作品のバックアップを保存しました。","backup.restored":"✅ 全作品のバックアップを復元しました。","backup.saveFailed":"❌ バックアップを保存できませんでした。","backup.readFailed":"❌ このバックアップファイルは読み込めませんでした。","backup.downloadHint":"Chromeのダウンロード一覧または端末の「Downloads」を確認してください。","save.saved":"保存しました ✓","save.auto":"変更は自動保存されます","save.failed":"保存に失敗しました — バックアップしてください","stage.new":"新しい工程","stage.max":"工程は最大{max}個までです。","stage.min":"工程は1つ以上必要です。","stage.rename":"名前を変更","stage.name":"工程名","stage.delete":"工程を削除","stage.reorder":"並べ替え","stage.confirmDelete":"工程「{name}」を削除しますか？","pages.total":"全{count}P","memo.pageNote":"{page}P 付箋","memo.deleteTodo":"TODOを削除","memo.empty":"該当するメモはありません。","memo.noText":"（メモ本文なし）","memo.go":"移動",
  "help.libraryTitle":"Libraryの使い方","help.create.title":"プロジェクトを作る","help.create.text":"右上の「＋」→「＋ プロジェクト」から新しいプロジェクトを作成します。","help.open.title":"タップして開く","help.open.text":"プロジェクト名をタップすると入力ページへ、フォルダ名をタップするとフォルダが開きます。","help.reorder.title":"≡で整理","help.reorder.text":"プロジェクトやフォルダの≡をドラッグすると、上下に自由に並び替えできます。プロジェクトはフォルダへ重ねて移動することもできます。","help.folder.title":"フォルダで整理","help.folder.text":"「＋」からフォルダを作成できます。プロジェクトをフォルダにまとめて整理できます。","help.edit.title":"プロジェクトを編集","help.edit.text":"プロジェクト右上の設定ボタンから、プロジェクト名・ページ・日付・工程を変更できます。","help.settings.title":"Library設定","help.settings.text":"Library右上の設定ボタンからアプリ設定を開けます。新規プロジェクトの初期値やテーマカラー、データ管理などを設定できます。","help.defaults.title":"新規プロジェクトのデフォルト","help.defaults.text":"新しく作るプロジェクトの制作ページと工程の初期値を設定できます。作成後はプロジェクトごとに変更できます。","help.theme.title":"テーマカラー","help.theme.text":"完了セルや選択状態などに使うアクセントカラーを変更できます。","help.trash.title":"ゴミ箱","help.trash.text":"削除したプロジェクトやフォルダはゴミ箱へ移動します。必要なら復元できます。","help.backup.title":"バックアップ","help.backup.text":"設定の「データ管理」から、Library全体をJSONファイルにバックアップ・復元できます。",
  "trash.title":"ゴミ箱","trash.move":"ゴミ箱へ","trash.empty":"空にする","trash.emptyState":"ゴミ箱は空です。","trash.restore":"元に戻す","trash.delete":"完全削除","trash.folderPrefix":"フォルダ：","trash.untitled":"無題","trash.confirmEmpty":"ゴミ箱の中身をすべて完全に削除しますか？\nこの操作は元に戻せません。",
  "create.label":"作成","create.project":"新しいプロジェクト","create.folder":"新しいフォルダ","memo.label":"ラベル","memo.labelPlaceholder":"表紙・扉・あとがき など","memo.textPlaceholder":"修正点・忘れたくないことなど","memo.todoPlaceholder":"チェック項目を追加","memo.delete":"付箋を削除","memo.all":"すべて","memo.none":"無色","color.red":"赤","color.yellow":"黄","color.blue":"青","color.green":"緑","color.none":"色なし"
 },
 en:{
  "library.title":"Library","library.newProject":"+ Project","library.newFolder":"+ Folder","library.projects":"Projects",
  "settings.title":"App Settings","settings.language":"Language","settings.defaults":"New Project Defaults","settings.pages":"Pages","settings.stages":"Stages","settings.addStage":"+ Add Stage","common.cancel":"Cancel","common.save":"Save","common.close":"Close","settings.note":"These are the initial values for new projects. Each project can be changed separately.","notes.title":"Notes",
  "settings.displayMode":"Display Mode","settings.displayModeNote":"Choose the appearance. Auto follows your device setting.","settings.themeColor":"Theme Color","settings.themeColorNote":"Used as the accent color for completed cells and selected states.","settings.cellShape":"Cell Shape","settings.cellShapeNote":"Changes only the cell appearance; the touch area stays square.","settings.dataManagement":"Data Management","settings.dataManagementNote":"Save all projects, folders, progress, notes, and work history in one JSON file.","settings.backup":"💾 Backup","settings.restore":"📂 Restore","backup.saved":"✅ All projects were backed up.","backup.restored":"✅ All projects were restored.","backup.saveFailed":"❌ Backup could not be saved.","backup.readFailed":"❌ This backup file could not be read.","backup.downloadHint":"Check Chrome downloads or the device Downloads folder.","save.saved":"Saved ✓","save.auto":"Changes are saved automatically","save.failed":"Save failed — export a backup","stage.new":"New stage","stage.max":"Up to {max} stages.","stage.min":"At least one stage is required.","stage.rename":"Rename","stage.name":"Stage name","stage.delete":"Delete stage","stage.reorder":"Reorder","stage.confirmDelete":"Delete stage “{name}”?","pages.total":"{count} pages","memo.pageNote":"Page {page} note","memo.deleteTodo":"Delete TODO","memo.empty":"No matching notes.","memo.noText":"(No note text)","memo.go":"Go",
  "help.libraryTitle":"Using Library","help.create.title":"Create a project","help.create.text":"Use + → + Project at the top right to create a new project.","help.open.title":"Tap to open","help.open.text":"Tap a project name to open its input page, or tap a folder name to open the folder.","help.reorder.title":"Reorder with ≡","help.reorder.text":"Drag ≡ on a project or folder to reorder items freely. You can also drag a project onto a folder to move it there.","help.folder.title":"Organize with folders","help.folder.text":"Create folders from the + button and organize projects inside them.","help.edit.title":"Edit a project","help.edit.text":"Use the settings button at the top right of a project to change its name, pages, dates, and stages.","help.settings.title":"Library settings","help.settings.text":"Open App Settings with the settings button at the top right of Library. You can set new-project defaults, the theme color, data management, and more.","help.defaults.title":"New Project Defaults","help.defaults.text":"Set the initial page count and stages for newly created projects. You can change them per project after creation.","help.theme.title":"Theme Color","help.theme.text":"Change the accent color used for completed cells, selected states, and other highlights.","help.trash.title":"Trash","help.trash.text":"Deleted projects and folders move to Trash and can be restored when needed.","help.backup.title":"Backup","help.backup.text":"Use Data Management in Settings to back up or restore the entire Library as a JSON file.",
  "trash.title":"Trash","trash.move":"Move to Trash","trash.empty":"Empty Trash","trash.emptyState":"Trash is empty.","trash.restore":"Restore","trash.delete":"Delete","trash.folderPrefix":"Folder: ","trash.untitled":"Untitled","trash.confirmEmpty":"Permanently delete everything in Trash? This cannot be undone.",
  "create.label":"Create","create.project":"New Project","create.folder":"New Folder","memo.label":"Label","memo.labelPlaceholder":"Cover, Title, After, etc.","memo.textPlaceholder":"Corrections, reminders, etc.","memo.todoPlaceholder":"Add checklist item","memo.delete":"Delete Note","memo.all":"All","memo.none":"No color","color.red":"Red","color.yellow":"Yellow","color.blue":"Blue","color.green":"Green","color.none":"No color"
 }
};
function uiLang(){return languageSettings?.language==="en"?"en":"ja"}
function t(key,vars){
 let value=I18N[uiLang()]?.[key]??I18N.ja[key]??key;
 if(vars)for(const [name,replacement] of Object.entries(vars))value=value.replaceAll(`{${name}}`,String(replacement));
 return value;
}
function applyLanguage(){
 document.documentElement.lang=uiLang();
 const set=(id,key)=>{const el=document.getElementById(id);if(el)el.textContent=t(key)};
 set("homeTitle","library.title");set("newProjectButton","library.newProject");set("settingsTitle","settings.title");
 set("settingsLanguageLabel","settings.language");set("settingsDefaultsTitle","settings.defaults");set("settingsPagesLabel","settings.pages");
 set("settingsStagesLabel","settings.stages");set("defaultStageAdd","settings.addStage");set("settingsCancel","common.cancel");set("settingsSave","common.save");set("settingsNote","settings.note");
 set("folderAdd","library.newFolder");set("backToProjects","library.projects");
 const memo=document.querySelector("#memoListButton .memo-list-label");if(memo)memo.textContent=t("notes.title");
}
