// Fillio UI translations. User-authored content is never passed through t().
const I18N={
 ja:{
  "library.title":"Library","library.newProject":"＋ プロジェクト","library.newFolder":"＋ フォルダ","library.projects":"作品一覧",
  "settings.title":"アプリ設定","settings.language":"言語","settings.defaults":"新規プロジェクトのデフォルト","settings.pages":"制作ページ","settings.stages":"工程","settings.addStage":"＋ 工程を追加","common.cancel":"キャンセル","common.save":"保存","common.close":"閉じる","settings.note":"新しいプロジェクトを作るときの初期値です。プロジェクトごとに変更できます。","notes.title":"メモ一覧",
  "settings.displayMode":"表示モード","settings.displayModeNote":"画面の明るさを選べます。自動は端末の設定に合わせます。","settings.themeColor":"テーマカラー","settings.themeColorNote":"完了セルや選択状態などのアクセントカラーに使われます。","settings.cellShape":"セル形状","settings.cellShapeNote":"タッチ領域はそのまま、セルの見た目だけを変更します。","settings.dataManagement":"データ管理","settings.dataManagementNote":"全作品・フォルダ・進捗・付箋・作業履歴を1つのJSONに保存します。","settings.backup":"💾 バックアップ","settings.restore":"📂 復元","backup.saved":"✅ 全作品のバックアップを保存しました。","backup.restored":"✅ 全作品のバックアップを復元しました。","backup.saveFailed":"❌ バックアップを保存できませんでした。","backup.readFailed":"❌ このバックアップファイルは読み込めませんでした。","backup.downloadHint":"Chromeのダウンロード一覧または端末の「Downloads」を確認してください。","save.saved":"保存しました ✓","save.auto":"変更は自動保存されます","save.failed":"保存に失敗しました — バックアップしてください","stage.new":"新しい工程","stage.max":"工程は最大{max}個までです。","stage.min":"工程は1つ以上必要です。","stage.rename":"名前を変更","stage.name":"工程名","stage.delete":"工程を削除","stage.reorder":"並べ替え","stage.confirmDelete":"工程「{name}」を削除しますか？","pages.total":"全{count}P","memo.pageNote":"{page}P 付箋","memo.deleteTodo":"TODOを削除","memo.empty":"該当するメモはありません。","memo.noText":"（メモ本文なし）","memo.go":"移動",
  "help.libraryTitle":"Libraryの使い方","help.create.title":"プロジェクトを作る","help.create.text":"右上の「＋」→「＋ プロジェクト」から新しいプロジェクトを作成します。","help.open.title":"タップして開く","help.open.text":"プロジェクト名をタップすると入力ページへ、フォルダ名をタップするとフォルダが開きます。","help.reorder.title":"≡で整理","help.reorder.text":"プロジェクトやフォルダの≡をドラッグすると、上下に自由に並び替えできます。プロジェクトはフォルダへ重ねて移動することもできます。","help.folder.title":"フォルダで整理","help.folder.text":"「＋」からフォルダを作成できます。プロジェクトをフォルダにまとめて整理できます。","help.edit.title":"プロジェクトを編集","help.edit.text":"プロジェクト右上の設定ボタンから、プロジェクト名・ページ・日付・工程を変更できます。","help.settings.title":"Library設定","help.settings.text":"Library右上の設定ボタンからアプリ設定を開けます。新規プロジェクトの初期値やテーマカラー、データ管理などを設定できます。","help.defaults.title":"新規プロジェクトのデフォルト","help.defaults.text":"新しく作るプロジェクトの制作ページと工程の初期値を設定できます。作成後はプロジェクトごとに変更できます。","help.theme.title":"テーマカラー","help.theme.text":"完了セルや選択状態などに使うアクセントカラーを変更できます。","help.trash.title":"ゴミ箱","help.trash.text":"削除したプロジェクトやフォルダはゴミ箱へ移動します。必要なら復元できます。","help.backup.title":"バックアップ","help.backup.text":"設定の「データ管理」から、Library全体をJSONファイルにバックアップ・復元できます。",
  "trash.title":"ゴミ箱","trash.move":"ゴミ箱へ","trash.empty":"空にする","trash.emptyState":"ゴミ箱は空です。","trash.restore":"元に戻す","trash.delete":"完全削除","trash.folderPrefix":"フォルダ：","trash.untitled":"無題","trash.confirmEmpty":"ゴミ箱の中身をすべて完全に削除しますか？\nこの操作は元に戻せません。",
  "create.label":"作成","create.project":"新しいプロジェクト","create.folder":"新しいフォルダ","memo.label":"ラベル","memo.labelPlaceholder":"表紙・扉・あとがき など","memo.textPlaceholder":"修正点・忘れたくないことなど","memo.todoPlaceholder":"チェック項目を追加","memo.delete":"付箋を削除","memo.all":"すべて","memo.none":"無色","color.red":"赤","color.yellow":"黄","color.blue":"青","color.green":"緑","color.none":"色なし",
  "editor.help.title":"使い方","editor.help.tap.title":"工程マスをタップ","editor.help.tap.text":"タップするたびに「未着手 → 着手 → 完了 → 未着手」と切り替わります。","editor.help.slide.title":"長押し＋スライド","editor.help.slide.text":"工程マスを約0.5秒長押しし、上下または左右になぞると範囲をプレビューできます。指を離すと確定します。振動したら開始です。","editor.help.page.title":"ページ番号をタップ","editor.help.page.text":"そのページに付箋メモを付けられます。赤・黄・青・緑で分類でき、「メモ一覧」から絞り込みやページ移動もできます。","editor.table":"工程表",
  "state.notStarted":"未着手","state.started":"着手","state.completed":"完了","project.label":"作品","project.edit":"作品編集","project.title":"作品名","project.startDate":"作業開始日","project.deadline":"締切予定日","project.stageSettings":"工程設定","project.stageNote":"工程名の変更・並び替え・追加・削除","common.none":"なし","memo.sticky":"付箋","memo.marker":"マーカー","folder.name":"フォルダ名","folder.rename":"フォルダ名を変更","settings.resetStages":"工程を初期設定に戻す","settings.resetStagesConfirm":"新規プロジェクト用の工程を初期設定に戻しますか？\n既存の作品には影響しません。","library.autoSave":"作品ごとの進捗・付箋・作業履歴は端末内に自動保存されます。","folder.renameAction":"名前変更","folder.deleteAction":"削除"
 },
 en:{
  "library.title":"Library","library.newProject":"+ Project","library.newFolder":"+ Folder","library.projects":"Projects",
  "settings.title":"App Settings","settings.language":"Language","settings.defaults":"New Project Defaults","settings.pages":"Pages","settings.stages":"Stages","settings.addStage":"+ Add Stage","common.cancel":"Cancel","common.save":"Save","common.close":"Close","settings.note":"These are the initial values for new projects. Each project can be changed separately.","notes.title":"Notes",
  "settings.displayMode":"Display Mode","settings.displayModeNote":"Choose the appearance. Auto follows your device setting.","settings.themeColor":"Theme Color","settings.themeColorNote":"Used as the accent color for completed cells and selected states.","settings.cellShape":"Cell Shape","settings.cellShapeNote":"Changes only the cell appearance; the touch area stays square.","settings.dataManagement":"Data Management","settings.dataManagementNote":"Save all projects, folders, progress, notes, and work history in one JSON file.","settings.backup":"💾 Backup","settings.restore":"📂 Restore","backup.saved":"✅ All projects were backed up.","backup.restored":"✅ All projects were restored.","backup.saveFailed":"❌ Backup could not be saved.","backup.readFailed":"❌ This backup file could not be read.","backup.downloadHint":"Check Chrome downloads or the device Downloads folder.","save.saved":"Saved ✓","save.auto":"Changes are saved automatically","save.failed":"Save failed — export a backup","stage.new":"New stage","stage.max":"Up to {max} stages.","stage.min":"At least one stage is required.","stage.rename":"Rename","stage.name":"Stage name","stage.delete":"Delete stage","stage.reorder":"Reorder","stage.confirmDelete":"Delete stage “{name}”?","pages.total":"{count} pages","memo.pageNote":"Page {page} note","memo.deleteTodo":"Delete TODO","memo.empty":"No matching notes.","memo.noText":"(No note text)","memo.go":"Go",
  "help.libraryTitle":"Using Library","help.create.title":"Create a project","help.create.text":"Use + → + Project at the top right to create a new project.","help.open.title":"Tap to open","help.open.text":"Tap a project name to open its input page, or tap a folder name to open the folder.","help.reorder.title":"Reorder with ≡","help.reorder.text":"Drag ≡ on a project or folder to reorder items freely. You can also drag a project onto a folder to move it there.","help.folder.title":"Organize with folders","help.folder.text":"Create folders from the + button and organize projects inside them.","help.edit.title":"Edit a project","help.edit.text":"Use the settings button at the top right of a project to change its name, pages, dates, and stages.","help.settings.title":"Library settings","help.settings.text":"Open App Settings with the settings button at the top right of Library. You can set new-project defaults, the theme color, data management, and more.","help.defaults.title":"New Project Defaults","help.defaults.text":"Set the initial page count and stages for newly created projects. You can change them per project after creation.","help.theme.title":"Theme Color","help.theme.text":"Change the accent color used for completed cells, selected states, and other highlights.","help.trash.title":"Trash","help.trash.text":"Deleted projects and folders move to Trash and can be restored when needed.","help.backup.title":"Backup","help.backup.text":"Use Data Management in Settings to back up or restore the entire Library as a JSON file.",
  "trash.title":"Trash","trash.move":"Move to Trash","trash.empty":"Empty Trash","trash.emptyState":"Trash is empty.","trash.restore":"Restore","trash.delete":"Delete","trash.folderPrefix":"Folder: ","trash.untitled":"Untitled","trash.confirmEmpty":"Permanently delete everything in Trash? This cannot be undone.",
  "create.label":"Create","create.project":"New Project","create.folder":"New Folder","memo.label":"Label","memo.labelPlaceholder":"Cover, Title, After, etc.","memo.textPlaceholder":"Corrections, reminders, etc.","memo.todoPlaceholder":"Add checklist item","memo.delete":"Delete Note","memo.all":"All","memo.none":"No color","color.red":"Red","color.yellow":"Yellow","color.blue":"Blue","color.green":"Green","color.none":"No color",
  "editor.help.title":"Help","editor.help.tap.title":"Tap a stage cell","editor.help.tap.text":"Each tap cycles: Not started → In progress → Complete → Not started.","editor.help.slide.title":"Long press + slide","editor.help.slide.text":"Long-press a stage cell for about 0.5 seconds, then slide vertically or horizontally to preview the range. Release to apply it. It starts when the device vibrates.","editor.help.page.title":"Tap a page number","editor.help.page.text":"Add a note to a page and classify it by red, yellow, blue or green. Filter notes and jump to pages from Notes.","editor.table":"Production Table",
  "state.notStarted":"Not started","state.started":"Started","state.completed":"Completed","project.label":"Project","project.edit":"Edit Project","project.title":"Project title","project.startDate":"Start Date","project.deadline":"Deadline","project.stageSettings":"Stage Settings","project.stageNote":"Rename, reorder, add or delete stages.","common.none":"None","memo.sticky":"Page Note","memo.marker":"Marker","folder.name":"Folder name","folder.rename":"Rename Folder","settings.resetStages":"Reset Stages","settings.resetStagesConfirm":"Reset the default stages for new projects?\nExisting projects will not be affected.","library.autoSave":"Project progress, notes and work history are saved automatically on this device.","folder.renameAction":"Rename","folder.deleteAction":"Delete"
 }
};
function uiLang(){return languageSettings?.language==="en"?"en":"ja"}
function t(key,vars){
 let value=I18N[uiLang()]?.[key]??I18N.ja[key]??key;
 if(vars)for(const [name,replacement] of Object.entries(vars))value=value.replaceAll(`{${name}}`,String(replacement));
 return value;
}
function applyLanguage(){
 document.documentElement.lang=uiLang();
 const set=(id,key)=>{const el=document.getElementById(id);if(!el)return;const label=el.querySelector?.("span");if(label)label.textContent=t(key);else el.textContent=t(key)};
 set("homeTitle","library.title");set("newProjectButton","library.newProject");set("settingsTitle","settings.title");
 set("settingsLanguageLabel","settings.language");set("settingsDefaultsTitle","settings.defaults");set("settingsPagesLabel","settings.pages");
 set("settingsStagesLabel","settings.stages");set("defaultStageAdd","settings.addStage");set("settingsCancel","common.cancel");set("settingsSave","common.save");set("settingsNote","settings.note");
 set("folderAdd","library.newFolder");set("backToProjects","library.projects");
 const memo=document.querySelector("#memoListButton .memo-list-label");if(memo)memo.textContent=t("notes.title");
 document.querySelectorAll("[data-i18n]").forEach(el=>{el.textContent=t(el.dataset.i18n)});
 document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>{el.setAttribute("placeholder",t(el.dataset.i18nPlaceholder))});
 const helpClose=document.getElementById("helpClose");if(helpClose)helpClose.setAttribute("aria-label",t("common.close"));
 const languageCancel=document.getElementById("languageCancel");if(languageCancel)languageCancel.setAttribute("aria-label",t("common.close"));
 const reset=document.getElementById("defaultStageReset");if(reset)reset.textContent=t("settings.resetStages");
 const stickyLabel=document.getElementById("stickyLabelCaption");if(stickyLabel)stickyLabel.textContent=t("memo.label");
 const stickyLabelInput=document.getElementById("stickyLabel");if(stickyLabelInput)stickyLabelInput.placeholder=t("memo.labelPlaceholder");
 const stickyText=document.getElementById("stickyText");if(stickyText)stickyText.placeholder=t("memo.textPlaceholder");
 const stickyTodo=document.getElementById("stickyTodoInput");if(stickyTodo)stickyTodo.placeholder=t("memo.todoPlaceholder");
 const closeMemo=document.getElementById("closeMemoList");if(closeMemo)closeMemo.setAttribute("aria-label",t("common.close"));
 const helpButton=document.getElementById("helpButton");if(helpButton)helpButton.setAttribute("aria-label",t("editor.help.title"));
 const filters=[["all","memo.all"],["none","memo.none"],["#f4a6a6","color.red"],["#f4dc8a","color.yellow"],["#9ec8f4","color.blue"],["#a9ddb0","color.green"]];
 filters.forEach(([value,key])=>{const el=document.querySelector(`.memo-filter[data-filter="${value}"]`);if(el)el.textContent=t(key)});
 const setText=(id,key)=>{const el=document.getElementById(id);if(el)el.textContent=t(key)};
 setText("displayModeTitle","settings.displayMode");setText("displayModeNote","settings.displayModeNote");
 setText("themeColorTitle","settings.themeColor");setText("themeColorNote","settings.themeColorNote");
 setText("cellShapeTitle","settings.cellShape");setText("cellShapeNote","settings.cellShapeNote");
 setText("dataManagementTitle","settings.dataManagement");setText("dataManagementNote","settings.dataManagementNote");
 setText("exportBackup","settings.backup");setText("importBackup","settings.restore");setText("libraryHelpTitle","help.libraryTitle");
 const hb=document.getElementById("libraryHelpButton");if(hb)hb.setAttribute("aria-label",t("help.libraryTitle"));
 const hc=document.getElementById("libraryHelpClose");if(hc)hc.setAttribute("aria-label",t("common.close"));
 const helpKeys=["create","open","reorder","folder","edit","settings","defaults","theme","trash","backup"];
 document.getElementById("libraryHelpModal")?.querySelectorAll(".help-item").forEach((it,i)=>{const key=helpKeys[i];if(!key)return;it.querySelector(".help-item-title").textContent=t(`help.${key}.title`);it.querySelector(".help-item-text").textContent=t(`help.${key}.text`)});
 const en=uiLang()==="en";
 document.querySelectorAll(".display-mode-option").forEach(btn=>{const label=en?btn.dataset.en:btn.dataset.ja;btn.textContent=label;btn.setAttribute("aria-label",label)});
 document.querySelectorAll(".theme-color-option").forEach(btn=>{const label=en?btn.dataset.en:btn.dataset.ja;btn.setAttribute("aria-label",label);btn.title=label;const x=btn.querySelector(".theme-option-label");if(x)x.textContent=label});
 document.querySelectorAll(".cell-shape-option").forEach(btn=>{const label=en?btn.dataset.en:btn.dataset.ja;btn.setAttribute("aria-label",label);btn.title=label;const x=btn.querySelector(".cell-shape-label");if(x)x.textContent=label});
}
